<?xml version="1.0" encoding="UTF-8"?><testrun name="FetchJeepTest" project="jeep-sales" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.promineotech.jeep.controller.FetchJeepTest" time="1.038" displayname="FetchJeepTest" uniqueid="[engine:junit-jupiter]/[class:com.promineotech.jeep.controller.FetchJeepTest]">
    <testcase name="testThatJeepsAreReturnedWhenValidModelAndTrimAreSupplied" classname="com.promineotech.jeep.controller.FetchJeepTest" time="1.038" displayname="testThatJeepsAreReturnedWhenValidModelAndTrimAreSupplied()" uniqueid="[engine:junit-jupiter]/[class:com.promineotech.jeep.controller.FetchJeepTest]/[method:testThatJeepsAreReturnedWhenValidModelAndTrimAreSupplied()]">
      <failure>
        <expected>200 OK</expected>
        <actual>404 NOT_FOUND</actual>
        org.opentest4j.AssertionFailedError: &#13;
expected: 200 OK&#13;
 but was: 404 NOT_FOUND&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)&#13;
	at com.promineotech.jeep.controller.FetchJeepTest.testThatJeepsAreReturnedWhenValidModelAndTrimAreSupplied(FetchJeepTest.java:29)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
